async function fetchBerry(id) {
  const res = await fetch(`https://pokeapi.co/api/v2/berry/${id}/`);
  const data = await res.json();
  console.log(data.name);
}

function traducir(texto) {
  const types = new Map([
    ["Cheri", "Zreza"],
    ["Chesto", "Atania"],
    ["Pecha", "Meloc"],
    ["Rawst", "Safre"],
    ["Aspear", "Perasi"],
    ["Leppa", "Zanama"],
    ["Oran", "Aranja"],
    ["Persim", "Caquic"],
    ["Lum", "Ziuela"],
    ["Sitrus", "Zidra"],
    ["Figy", "Higog"],
    ["Wiki", "Wiki"],
    ["Mago", "Ango"],
    ["Aguav", "Guaya"],
    ["Iapapa", "Pabaya"],
    ["Razz", "Frambu"],
    ["Bluk", "Oram"],
    ["Nanab", "Latano"],
    ["Wepear", "Peragu"],
    ["Pinap", "Pinia"],
    ["Pomeg", "Grana"],
    ["Kelpsy", "Algama"],
    ["Qualot", "Ispero"],
    ["Hondew", "Meluce"],
    ["Grepa", "Uvav"],
    ["Tamato", "Tamate"],
    ["Cornn", "Mais"],
    ["Magost", "Aostan"],
    ["Rabuta", "Rautan"],
    ["Nomel", "Monli"],
    ["Spelon", "Wikano"],
    ["Pamtre", "Plama"],
    ["Watmel", "Sambia"],
    ["Durin", "Rudion"],
    ["Belue", "Andano"],
    ["Occa", "Caoca"],
    ["Passho", "Pasio"],
    ["Wacan", "Gualot"],
    ["Rindo", "Tamar"],
    ["Yache", "Rimoya"],
    ["Chople", "Pomaro"],
    ["Kebia", "Kebia"],
    ["Shuca", "Acardo"],
    ["Coba", "Kouba"],
    ["Payapa", "Payapa"],
    ["Tanga", "Yecana"],
    ["Charti", "Alcho"],
    ["Kasib", "Drasi"],
    ["Haban", "Anjiro"],
    ["Colbur", "Dillo"],
    ["Babiri", "Baribá"],
    ["Chilan", "Chilan"],
    ["Liechi", "Lichi"],
    ["Ganlon", "Gonlan"],
    ["Salac", "Aslac"],
    ["Petaya", "Yapati"],
    ["Apicot", "Aricoc"],
    ["Lansat", "Zonlan"],
    ["Starf", "Arabol"],
    ["Enigma", "Enigma"],
    ["Micle", "Lagro"],
    ["Custap", "Chiri"],
    ["Jaboca", "Jaboca"],
    ["Rowap", "Magua"],
  ]);
  if (types.has(texto)) {
    texto = types.get(texto);
  }
  return texto;
}
