async function fetchBerry(id) {
  const res = await fetch(`https://pokeapi.co/api/v2/berry/${id}/`);
  const data = await res.json();
  console.log(data.name);
}

function traducir(texto) {
  const types = new Map([
    ["Cheri Berry", "Baya Zreza"],
    ["Chesto Berry", "Baya Atania"],
    ["Pecha Berry", "Baya Meloc"],
    ["Rawst Berry", "Baya Safre"],
    ["Aspear Berry", "Baya Perasi"],
    ["Leppa Berry", "Baya Zanama"],
    ["Oran Berry", "Baya Aranja"],
    ["Persim Berry", "Baya Caquic"],
    ["Lum Berry", "Baya Ziuela"],
    ["Sitrus Berry", "Baya Zidra"],
    ["Figy Berry", "Baya Higog"],
    ["Wiki Berry", "Baya Wiki"],
    ["Mago Berry", "Baya Ango"],
    ["Aguav Berry", "Baya Guaya"],
    ["Iapapa Berry", "Baya Pabaya"],
    ["Razz Berry", "Baya Frambu"],
    ["Bluk Berry", "Baya Oram"],
    ["Nanab Berry", "Baya Latano"],
    ["Wepear Berry", "Baya Peragu"],
    ["Pinap Berry", "Baya Pinia"],
    ["Pomeg Berry", "Baya Grana"],
    ["Kelpsy Berry", "Baya Algama"],
    ["Qualot Berry", "Baya Ispero"],
    ["Hondew Berry", "Baya Meluce"],
    ["Grepa Berry", "Baya Uvav"],
    ["Tamato Berry", "Baya Tamate"],
    ["Cornn Berry", "Baya Mais"],
    ["Magost Berry", "Baya Aostan"],
    ["Rabuta Berry", "Baya Rautan"],
    ["Nomel Berry", "Baya Monli"],
    ["Spelon Berry", "Baya Wikano"],
    ["Pamtre Berry", "Baya Plama"],
    ["Watmel Berry", "Baya Sambia"],
    ["Durin Berry", "Baya Rudion"],
    ["Belue Berry", "Baya Andano"],
    ["Occa Berry", "Baya Caoca"],
    ["Passho Berry", "Baya Pasio"],
    ["Wacan Berry", "Baya Gualot"],
    ["Rindo Berry", "Baya Tamar"],
    ["Yache Berry", "Baya Rimoya"],
    ["Chople Berry", "Baya Pomaro"],
    ["Kebia Berry", "Baya Kebia"],
    ["Shuca Berry", "Baya Acardo"],
    ["Coba Berry", "Baya Kouba"],
    ["Payapa Berry", "Baya Payapa"],
    ["Tanga Berry", "Baya Yecana"],
    ["Charti Berry", "Baya Alcho"],
    ["Kasib Berry", "Baya Drasi"],
    ["Haban Berry", "Baya Anjiro"],
    ["Colbur Berry", "Baya Dillo"],
    ["Babiri Berry", "Baya Baribá"],
    ["Chilan Berry", "Baya Chilan"],
    ["Liechi Berry", "Baya Lichi"],
    ["Ganlon Berry", "Baya Gonlan"],
    ["Salac Berry", "Baya Aslac"],
    ["Petaya Berry", "Baya Yapati"],
    ["Apicot Berry", "Baya Aricoc"],
    ["Lansat Berry", "Baya Zonlan"],
    ["Starf Berry", "Baya Arabol"],
    ["Enigma Berry", "Baya Enigma"],
    ["Micle Berry", "Baya Lagro"],
    ["Custap Berry", "Baya Chiri"],
    ["Jaboca Berry", "Baya Jaboca"],
    ["Rowap Berry", "Baya Magua"],
  ]);
  if (types.has(texto)) {
    texto = types.get(texto);
  }
  return texto;
}
